# Generated by Django 3.1.4 on 2020-12-10 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a city name for a contract', max_length=100)),
                ('zakupkiId', models.CharField(help_text='Enter an id from zakupki.gov.ru', max_length=50)),
                ('dateStart', models.DateField()),
                ('dateEnd', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a task name', max_length=200)),
                ('description', models.TextField(help_text='Enter a task description')),
                ('datetimeStart', models.DateTimeField()),
                ('datetimeEnd', models.DateTimeField()),
                ('status', models.CharField(help_text='Enter a task status', max_length=1)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.contract')),
            ],
        ),
    ]
