# Generated by Django 3.1.4 on 2020-12-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(help_text='Enter a task status 0 - active, 1 - completed', max_length=1),
        ),
    ]
