# Generated by Django 3.1.4 on 2020-12-10 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='name',
            new_name='contractName',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='name',
            new_name='documentName',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='taskName',
        ),
    ]
