# Generated by Django 3.1.4 on 2020-12-11 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20201211_0103'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contract',
            table='Contract',
        ),
    ]
