# Generated by Django 3.1.4 on 2020-12-16 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20201211_0411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='contract',
            new_name='contract1',
        ),
    ]
