# Generated by Django 3.1.4 on 2020-12-16 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20201217_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='contract1',
            new_name='taskContractName',
        ),
    ]
