# Generated by Django 3.1.4 on 2020-12-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20201217_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='linkToZakupkigov',
            field=models.TextField(default='https://zakupki.gov.ru/epz/main/public/home.html', help_text='Enter an link to zakupki.gov.ru'),
        ),
    ]
