# Generated by Django 3.1.4 on 2020-12-17 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_contract_linktozakupkigov'),
        ('catalog', '0008_task_followers'),
    ]

    operations = [
    ]
