# Generated by Django 3.1.4 on 2020-12-20 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0009_merge_20201217_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='currentUsers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
