# Generated by Django 3.1.4 on 2020-12-25 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20201225_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='followers',
            new_name='performer',
        ),
    ]
